# Generated by Django 5.2.9 on 2026-01-17 17:56

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='es_por_peso',
            field=models.BooleanField(default=False, help_text='Si está marcado, el producto se vende por peso (Kg) y acepta decimales'),
        ),
        migrations.AlterField(
            model_name='movimientoinventario',
            name='cantidad',
            field=models.DecimalField(decimal_places=3, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))]),
        ),
        migrations.AlterField(
            model_name='movimientoinventario',
            name='cantidad_anterior',
            field=models.DecimalField(decimal_places=3, max_digits=10),
        ),
        migrations.AlterField(
            model_name='movimientoinventario',
            name='cantidad_nueva',
            field=models.DecimalField(decimal_places=3, max_digits=10),
        ),
        migrations.AlterField(
            model_name='producto',
            name='cantidad',
            field=models.DecimalField(decimal_places=3, default=Decimal('0.000'), help_text='Cantidad disponible en inventario', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.000'))]),
        ),
        migrations.AlterField(
            model_name='producto',
            name='stock_minimo',
            field=models.DecimalField(decimal_places=3, default=Decimal('5.000'), help_text='Cantidad mínima de alerta', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.000'))]),
        ),
    ]
