# Generated by Django 5.2.9 on 2026-01-17 18:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
        ('ventas', '0002_alter_itemfactura_cantidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factura',
            name='cliente',
            field=models.ForeignKey(blank=True, help_text='Cliente de la venta. Si es None, es un cliente casual.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='facturas', to='clientes.cliente'),
        ),
    ]
