# Generated by Django 5.2.9 on 2026-02-17 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0003_alter_factura_cliente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pago',
            name='metodo',
            field=models.CharField(choices=[('EFECTIVO_USD', 'Efectivo USD'), ('EFECTIVO_BS', 'Efectivo Bs'), ('TRANSFERENCIA', 'Transferencia Bancaria'), ('PUNTO_VENTA', 'Punto de Venta'), ('PAGO_MOVIL', 'Pago Móvil'), ('ZELLE', 'Zelle'), ('MIXTO', 'Mixto'), ('OTRO', 'Otro')], max_length=20),
        ),
    ]
