# Generated by Django 5.2.9 on 2026-01-26 18:57

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
        ('inventario', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(editable=False, max_length=20, unique=True)),
                ('tipo_venta', models.CharField(choices=[('CONTADO', 'Contado'), ('CREDITO', 'Crédito')], default='CONTADO', max_length=10)),
                ('subtotal_usd', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('descuento_usd', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('total_usd', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('tasa_cambio', models.DecimalField(decimal_places=2, max_digits=12)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('PARCIAL', 'Pago Parcial'), ('PAGADA', 'Pagada'), ('ANULADA', 'Anulada')], default='PENDIENTE', max_length=10)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notas', models.TextField(blank=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='facturas', to='clientes.cliente')),
                ('vendedor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Factura',
                'verbose_name_plural': 'Facturas',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='ItemFactura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=3, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))])),
                ('precio_unitario_usd', models.DecimalField(decimal_places=2, max_digits=10)),
                ('descuento_usd', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('factura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='ventas.factura')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventario.producto')),
            ],
            options={
                'verbose_name': 'Item de Factura',
                'verbose_name_plural': 'Items de Factura',
            },
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metodo', models.CharField(choices=[('EFECTIVO_USD', 'Efectivo USD'), ('EFECTIVO_BS', 'Efectivo Bs'), ('TRANSFERENCIA', 'Transferencia Bancaria'), ('PUNTO_VENTA', 'Punto de Venta'), ('PAGO_MOVIL', 'Pago Móvil'), ('ZELLE', 'Zelle'), ('OTRO', 'Otro')], max_length=20)),
                ('monto_recibido_bs', models.DecimalField(decimal_places=2, help_text='Monto recibido en bolívares (o convertido a Bs si es USD)', max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('monto_bs', models.DecimalField(decimal_places=2, help_text='Monto aplicado a la factura en Bs', max_digits=15)),
                ('vuelto_bs', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Vuelto en bolívares', max_digits=15)),
                ('tasa_cambio', models.DecimalField(decimal_places=2, max_digits=12)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('COMPLETADO', 'Completado'), ('ANULADO', 'Anulado')], default='COMPLETADO', max_length=10)),
                ('referencia', models.CharField(blank=True, help_text='Número de referencia bancaria', max_length=100)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('cajero', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('factura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='ventas.factura')),
            ],
            options={
                'verbose_name': 'Pago',
                'verbose_name_plural': 'Pagos',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='TasaCambio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tasa', models.DecimalField(decimal_places=2, help_text='Bolívares por cada dólar', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('fecha', models.DateField(auto_now_add=True, unique=True)),
                ('fuente', models.CharField(default='BCV', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Tasa de Cambio',
                'verbose_name_plural': 'Tasas de Cambio',
                'ordering': ['-fecha'],
                'indexes': [models.Index(fields=['-fecha'], name='ventas_tasa_fecha_b5a74c_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='factura',
            index=models.Index(fields=['numero'], name='ventas_fact_numero_fa0c4c_idx'),
        ),
        migrations.AddIndex(
            model_name='factura',
            index=models.Index(fields=['-fecha'], name='ventas_fact_fecha_1c6235_idx'),
        ),
        migrations.AddIndex(
            model_name='factura',
            index=models.Index(fields=['estado'], name='ventas_fact_estado_a26c96_idx'),
        ),
    ]
